//! Embeds the finished static site, and the blog, into the binary.
//!
//! The site is built elsewhere and lands in `site/` (override with
//! `GRUND_WEBSITE_SITE_DIR`). The blog is markdown under `blog/posts/`,
//! rendered here with the templates in `blog/templates/` (src/blog.rs). This
//! script walks both once per build and, for every file, records its URL path,
//! content type and content hash, and writes brotli and gzip variants when they
//! are smaller. The server then answers from a static table: the `scratch`
//! image has no filesystem to read, and nothing is compressed on the request
//! path.
//!
//! It emits the public site as `PUBLIC_VARIANTS`: one table for before the
//! first scheduled post (`publish_at`) and one from each scheduled moment on,
//! so the server can switch at that moment with nothing to rebuild.
//! `DRAFT_VARIANTS` holds one table with every draft and scheduled post, served
//! only when GRUND_WEBSITE_BLOG_DRAFTS is on. All tables share one copy of
//! every file's bytes.
//!
//! It refuses, naming the file, anything that would otherwise surface as a
//! wrong response in production: a missing `index.html` or `404.html`, an
//! extension with no known content type, a path a URL cannot name plainly, a
//! post with bad front matter, or a post whose path a site file already has.

use std::{
    collections::BTreeMap,
    env,
    fmt::Write as _,
    fs,
    io::Write as _,
    path::{Path, PathBuf},
};

use sha2::{Digest, Sha256};

#[path = "src/blog.rs"]
#[allow(dead_code)]
mod blog;

/// Below this, compression costs more in headers and CPU than it saves.
const MIN_COMPRESS_BYTES: usize = 256;

fn main() {
    println!("cargo:rerun-if-env-changed=GRUND_WEBSITE_SITE_DIR");
    println!("cargo:rerun-if-env-changed=GRUND_WEBSITE_REVISION");
    println!("cargo:rerun-if-env-changed=CI_COMMIT_SHA");
    println!("cargo:rerun-if-changed=src/blog.rs");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let site_dir = env::var("GRUND_WEBSITE_SITE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest.join("site"));
    let site_dir = if site_dir.is_absolute() {
        site_dir
    } else {
        manifest.join(site_dir)
    };
    // A directory here makes cargo rescan the whole tree for changes.
    println!("cargo:rerun-if-changed={}", site_dir.display());
    let blog_dir = manifest.join("blog");
    println!("cargo:rerun-if-changed={}", blog_dir.display());

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let blobs = out.join("site");
    let _ = fs::remove_dir_all(&blobs);
    fs::create_dir_all(&blobs).unwrap();

    let mut site_files = Vec::new();
    collect(&site_dir, &site_dir, &mut site_files);
    for required in ["index.html", "404.html"] {
        if !site_files.iter().any(|(path, _)| path == required) {
            panic!(
                "{} has no {required}; the site contract requires it",
                site_dir.display()
            );
        }
    }
    let site: Vec<(String, Vec<u8>)> = site_files
        .into_iter()
        .map(|(path, source)| (path, fs::read(source).unwrap()))
        .collect();

    let posts = read_posts(&blog_dir);
    let mut store = Blobs::new(blobs);
    let mut public_variants = String::from("&[\n");
    let moments = std::iter::once(i64::MIN).chain(blog::schedule(&posts));
    for from in moments {
        let files = with_blog(&site, &posts, &blog_dir, blog::View::Public { at: from });
        let (entries, digest) = table(&files, &mut store);
        let from = if from == i64::MIN {
            "i64::MIN".to_string()
        } else {
            from.to_string()
        };
        writeln!(
            public_variants,
            "Variant {{ from: {from}, entries: {entries}, digest: {digest:?} }},"
        )
        .unwrap();
    }
    public_variants.push(']');
    let drafts = with_blog(&site, &posts, &blog_dir, blog::View::Drafts);
    let (draft_entries, draft_digest) = table(&drafts, &mut store);

    let revision = env::var("GRUND_WEBSITE_REVISION")
        .or_else(|_| env::var("CI_COMMIT_SHA"))
        .unwrap_or_else(|_| "unknown".into());
    let generated = format!(
        "// Generated by build.rs from {site} and {blog}. Do not edit.\n\
         {statics}\
         pub static PUBLIC_VARIANTS: &[Variant] = {public_variants};\n\
         pub static DRAFT_VARIANTS: &[Variant] = &[Variant {{ from: i64::MIN, entries: {draft_entries}, digest: {draft_digest:?} }}];\n\
         pub const REVISION: &str = {revision:?};\n",
        site = site_dir.display(),
        blog = blog_dir.display(),
        statics = store.statics,
    );
    fs::write(out.join("site_entries.rs"), generated).unwrap();
}

/// Every post under `blog/posts/`, parsed. A bad post fails the build,
/// naming the file.
fn read_posts(blog_dir: &Path) -> Vec<blog::Post> {
    let dir = blog_dir.join("posts");
    let Ok(entries) = fs::read_dir(&dir) else {
        return Vec::new();
    };
    let mut posts = Vec::new();
    for entry in entries {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        if name.starts_with('.') {
            continue;
        }
        let Some(slug) = name.strip_suffix(".md") else {
            panic!("{}: blog/posts/ holds only .md posts", path.display());
        };
        let source =
            fs::read_to_string(&path).unwrap_or_else(|error| panic!("{}: {error}", path.display()));
        let post = blog::parse(slug, &source)
            .unwrap_or_else(|error| panic!("{}: {error}", path.display()));
        posts.push(post);
    }
    posts
}

/// The site plus the blog, sorted by path. A post may not take a path that a
/// file under `site/` already has.
fn with_blog(
    site: &[(String, Vec<u8>)],
    posts: &[blog::Post],
    blog_dir: &Path,
    view: blog::View,
) -> Vec<(String, Vec<u8>)> {
    let template = |name: &str| {
        let path = blog_dir.join("templates").join(name);
        fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!("{}: {error} (the blog needs its templates)", path.display())
        })
    };
    let mut files: Vec<(String, Vec<u8>)> = site.to_vec();
    if !posts.is_empty() {
        let (post, index) = (template("post.html"), template("index.html"));
        let templates = blog::Templates {
            post: &post,
            index: &index,
        };
        let rendered =
            blog::render(posts, &templates, view).unwrap_or_else(|error| panic!("{error}"));
        for file in rendered {
            if files.iter().any(|(path, _)| *path == file.path) {
                panic!(
                    "{}: the blog generates this path, and site/ already has it",
                    file.path
                );
            }
            files.push((file.path, file.bytes));
        }
    }
    files.sort_by(|a, b| a.0.cmp(&b.0));
    files
}

/// One stored copy of each distinct file content, and its variants, emitted
/// as `static`s that both tables point at.
struct Blobs {
    dir: PathBuf,
    statics: String,
    /// Content hash -> (identity, br, gzip) static names.
    seen: BTreeMap<String, (String, String, String)>,
}

impl Blobs {
    fn new(dir: PathBuf) -> Self {
        Self {
            dir,
            statics: String::new(),
            seen: BTreeMap::new(),
        }
    }

    fn store(&mut self, hash: &str, content_type: &str, bytes: &[u8]) -> (String, String, String) {
        if let Some(names) = self.seen.get(hash) {
            return names.clone();
        }
        let index = self.seen.len();
        let identity = self.dir.join(format!("{index}"));
        fs::write(&identity, bytes).unwrap();
        let (br, gzip) = if compressible(content_type) && bytes.len() >= MIN_COMPRESS_BYTES {
            (
                keep_if_smaller(&self.dir, index, "br", bytes, brotli(bytes)),
                keep_if_smaller(&self.dir, index, "gz", bytes, gzip(bytes)),
            )
        } else {
            (None, None)
        };
        let name = format!("BLOB_{index}");
        writeln!(
            self.statics,
            "static {name}: &[u8] = include_bytes!({:?});",
            identity.display().to_string()
        )
        .unwrap();
        let variant = |suffix: &str, path: Option<PathBuf>, statics: &mut String| match path {
            Some(path) => {
                let variant = format!("{name}_{suffix}");
                writeln!(
                    statics,
                    "static {variant}: &[u8] = include_bytes!({:?});",
                    path.display().to_string()
                )
                .unwrap();
                format!("Some({variant})")
            }
            None => "None".into(),
        };
        let br = variant("BR", br, &mut self.statics);
        let gzip = variant("GZ", gzip, &mut self.statics);
        let names = (name, br, gzip);
        self.seen.insert(hash.to_string(), names.clone());
        names
    }
}

/// One table's source, and its digest over every path and hash.
fn table(files: &[(String, Vec<u8>)], store: &mut Blobs) -> (String, String) {
    let mut table = String::from("&[\n");
    let mut digest = Sha256::new();
    for (path, bytes) in files {
        let content_type = content_type(path).unwrap_or_else(|| {
            panic!(
                "{path}: no content type is known for this extension; add it to build.rs \
                 deliberately rather than serving application/octet-stream"
            )
        });
        let hash = hex(&Sha256::digest(bytes))[..32].to_string();
        digest.update(path.as_bytes());
        digest.update([0]);
        digest.update(hash.as_bytes());
        digest.update([0]);
        let (identity, br, gzip) = store.store(&hash, content_type, bytes);
        writeln!(
            table,
            "    Entry {{ path: {path:?}, content_type: {content_type:?}, hash: {hash:?}, \
             identity: {identity}, br: {br}, gzip: {gzip} }},",
        )
        .unwrap();
    }
    table.push(']');
    (table, hex(&digest.finalize()))
}

/// Walks `dir`, returning `(url path, file)` pairs. Dotfiles are skipped, except
/// `.well-known/`, which is a real URL namespace (security.txt, ACME, and so on).
fn collect(root: &Path, dir: &Path, files: &mut Vec<(String, PathBuf)>) {
    let entries = fs::read_dir(dir)
        .unwrap_or_else(|error| panic!("cannot read site directory {}: {error}", dir.display()));
    for entry in entries {
        let entry = entry.unwrap();
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') && name != ".well-known" {
            continue;
        }
        let kind = entry.file_type().unwrap();
        if kind.is_dir() {
            collect(root, &path, files);
        } else if kind.is_file() {
            let relative = path.strip_prefix(root).unwrap();
            let url: Vec<String> = relative
                .components()
                .map(|component| component.as_os_str().to_string_lossy().into_owned())
                .collect();
            let url = url.join("/");
            if !url.split('/').all(plain_segment) {
                panic!(
                    "{url}: site paths are limited to ASCII letters, digits and . _ - ~ @ + \
                     so that the URL and the file name are the same string"
                );
            }
            files.push((url, path));
        } else {
            panic!(
                "{}: symlinks and special files are not part of the site contract",
                path.display()
            );
        }
    }
}

fn plain_segment(segment: &str) -> bool {
    !segment.is_empty()
        && segment != "."
        && segment != ".."
        && segment
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"._-~@+".contains(&b))
}

fn content_type(path: &str) -> Option<&'static str> {
    let extension = path.rsplit_once('.')?.1.to_ascii_lowercase();
    Some(match extension.as_str() {
        "html" => "text/html; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "json" => "application/json",
        "map" => "application/json",
        "webmanifest" => "application/manifest+json",
        "txt" => "text/plain; charset=utf-8",
        // Shell scripts (install.sh) are served as text: readable in a browser,
        // and exactly the bytes `curl | sh` runs.
        "sh" => "text/plain; charset=utf-8",
        "xml" => "application/xml",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "wasm" => "application/wasm",
        "pdf" => "application/pdf",
        "mp4" => "video/mp4",
        "webm" => "video/webm",
        _ => return None,
    })
}

/// Already-compressed formats (images, fonts, video) gain nothing.
fn compressible(content_type: &str) -> bool {
    content_type.starts_with("text/")
        || content_type.starts_with("application/json")
        || content_type.starts_with("application/manifest+json")
        || content_type.starts_with("application/xml")
        || content_type.starts_with("application/wasm")
        || content_type.starts_with("image/svg+xml")
        || content_type.starts_with("image/x-icon")
}

fn brotli(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    let params = brotli::enc::BrotliEncoderParams {
        quality: 11,
        ..Default::default()
    };
    brotli::BrotliCompress(&mut &bytes[..], &mut out, &params).unwrap();
    out
}

fn gzip(bytes: &[u8]) -> Vec<u8> {
    let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
    encoder.write_all(bytes).unwrap();
    encoder.finish().unwrap()
}

/// A variant is only worth a second representation (and a Vary header) when it
/// saves at least a tenth of the bytes.
fn keep_if_smaller(
    blobs: &Path,
    index: usize,
    suffix: &str,
    original: &[u8],
    compressed: Vec<u8>,
) -> Option<PathBuf> {
    if compressed.len() * 10 > original.len() * 9 {
        return None;
    }
    let path = blobs.join(format!("{index}.{suffix}"));
    fs::write(&path, compressed).unwrap();
    Some(path)
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().fold(String::new(), |mut out, byte| {
        let _ = write!(out, "{byte:02x}");
        out
    })
}
