//! Embeds the finished static site into the binary.
//!
//! The site is built elsewhere and lands in `site/` (override with
//! `GRUND_WEBSITE_SITE_DIR`). This script walks it once per build and, for every
//! file, records its URL path, content type and content hash, and writes brotli
//! and gzip variants when they are smaller. The server then answers from a
//! static table: the `scratch` image has no filesystem to read, and nothing is
//! compressed on the request path.
//!
//! It refuses, naming the file, anything that would otherwise surface as a
//! wrong response in production: a missing `index.html` or `404.html`, an
//! extension with no known content type, or a path a URL cannot name plainly.
//! See REQUIREMENTS.md for the contract.

use std::{
    env,
    fmt::Write as _,
    fs,
    io::Write as _,
    path::{Path, PathBuf},
};

use sha2::{Digest, Sha256};

/// Below this, compression costs more in headers and CPU than it saves.
const MIN_COMPRESS_BYTES: usize = 256;

fn main() {
    println!("cargo:rerun-if-env-changed=GRUND_WEBSITE_SITE_DIR");
    println!("cargo:rerun-if-env-changed=GRUND_WEBSITE_REVISION");
    println!("cargo:rerun-if-env-changed=CI_COMMIT_SHA");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let site_dir = env::var("GRUND_WEBSITE_SITE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest.join("site"));
    let site_dir = if site_dir.is_absolute() {
        site_dir
    } else {
        manifest.join(site_dir)
    };
    // A directory here makes cargo rescan the whole tree for changes.
    println!("cargo:rerun-if-changed={}", site_dir.display());

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let blobs = out.join("site");
    let _ = fs::remove_dir_all(&blobs);
    fs::create_dir_all(&blobs).unwrap();

    let mut files = Vec::new();
    collect(&site_dir, &site_dir, &mut files);
    files.sort();

    for required in ["index.html", "404.html"] {
        if !files.iter().any(|(path, _)| path == required) {
            panic!(
                "{} has no {required}; the site contract requires it (see REQUIREMENTS.md)",
                site_dir.display()
            );
        }
    }

    let mut table = String::from("&[\n");
    let mut digest = Sha256::new();
    for (index, (path, source)) in files.iter().enumerate() {
        let bytes = fs::read(source).unwrap();
        let content_type = content_type(path).unwrap_or_else(|| {
            panic!(
                "{path}: no content type is known for this extension; add it to build.rs \
                 deliberately rather than serving application/octet-stream"
            )
        });
        let hash = hex(&Sha256::digest(&bytes))[..32].to_string();
        digest.update(path.as_bytes());
        digest.update([0]);
        digest.update(hash.as_bytes());
        digest.update([0]);

        let identity = blobs.join(format!("{index}"));
        fs::write(&identity, &bytes).unwrap();
        let (br, gzip) = if compressible(content_type) && bytes.len() >= MIN_COMPRESS_BYTES {
            (
                keep_if_smaller(&blobs, index, "br", &bytes, brotli(&bytes)),
                keep_if_smaller(&blobs, index, "gz", &bytes, gzip(&bytes)),
            )
        } else {
            (None, None)
        };

        writeln!(
            table,
            "    Entry {{ path: {path:?}, content_type: {content_type:?}, hash: {hash:?}, \
             identity: include_bytes!({identity:?}), br: {br}, gzip: {gzip} }},",
            identity = identity.display().to_string(),
            br = optional_include(br),
            gzip = optional_include(gzip),
        )
        .unwrap();
    }
    table.push(']');

    let revision = env::var("GRUND_WEBSITE_REVISION")
        .or_else(|_| env::var("CI_COMMIT_SHA"))
        .unwrap_or_else(|_| "unknown".into());
    let generated = format!(
        "// Generated by build.rs from {site}. Do not edit.\n\
         pub const ENTRIES: &[Entry] = {table};\n\
         pub const SITE_DIGEST: &str = {digest:?};\n\
         pub const REVISION: &str = {revision:?};\n",
        site = site_dir.display(),
        digest = hex(&digest.finalize()),
    );
    fs::write(out.join("site_entries.rs"), generated).unwrap();
}

/// Walks `dir`, returning `(url path, file)` pairs. Dotfiles are skipped, except
/// `.well-known/`, which is a real URL namespace (security.txt, ACME, and so on).
fn collect(root: &Path, dir: &Path, files: &mut Vec<(String, PathBuf)>) {
    let entries = fs::read_dir(dir)
        .unwrap_or_else(|error| panic!("cannot read site directory {}: {error}", dir.display()));
    for entry in entries {
        let entry = entry.unwrap();
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') && name != ".well-known" {
            continue;
        }
        let kind = entry.file_type().unwrap();
        if kind.is_dir() {
            collect(root, &path, files);
        } else if kind.is_file() {
            let relative = path.strip_prefix(root).unwrap();
            let url: Vec<String> = relative
                .components()
                .map(|component| component.as_os_str().to_string_lossy().into_owned())
                .collect();
            let url = url.join("/");
            if !url.split('/').all(plain_segment) {
                panic!(
                    "{url}: site paths are limited to ASCII letters, digits and . _ - ~ @ + \
                     so that the URL and the file name are the same string"
                );
            }
            files.push((url, path));
        } else {
            panic!(
                "{}: symlinks and special files are not part of the site contract",
                path.display()
            );
        }
    }
}

fn plain_segment(segment: &str) -> bool {
    !segment.is_empty()
        && segment != "."
        && segment != ".."
        && segment
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"._-~@+".contains(&b))
}

fn content_type(path: &str) -> Option<&'static str> {
    let extension = path.rsplit_once('.')?.1.to_ascii_lowercase();
    Some(match extension.as_str() {
        "html" => "text/html; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "json" => "application/json",
        "map" => "application/json",
        "webmanifest" => "application/manifest+json",
        "txt" => "text/plain; charset=utf-8",
        // Shell scripts (install.sh) are served as text: readable in a browser,
        // and exactly the bytes `curl | sh` runs.
        "sh" => "text/plain; charset=utf-8",
        "xml" => "application/xml",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "wasm" => "application/wasm",
        "pdf" => "application/pdf",
        "mp4" => "video/mp4",
        "webm" => "video/webm",
        _ => return None,
    })
}

/// Already-compressed formats (images, fonts, video) gain nothing.
fn compressible(content_type: &str) -> bool {
    content_type.starts_with("text/")
        || content_type.starts_with("application/json")
        || content_type.starts_with("application/manifest+json")
        || content_type.starts_with("application/xml")
        || content_type.starts_with("application/wasm")
        || content_type.starts_with("image/svg+xml")
        || content_type.starts_with("image/x-icon")
}

fn brotli(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    let params = brotli::enc::BrotliEncoderParams {
        quality: 11,
        ..Default::default()
    };
    brotli::BrotliCompress(&mut &bytes[..], &mut out, &params).unwrap();
    out
}

fn gzip(bytes: &[u8]) -> Vec<u8> {
    let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
    encoder.write_all(bytes).unwrap();
    encoder.finish().unwrap()
}

/// A variant is only worth a second representation (and a Vary header) when it
/// saves at least a tenth of the bytes.
fn keep_if_smaller(
    blobs: &Path,
    index: usize,
    suffix: &str,
    original: &[u8],
    compressed: Vec<u8>,
) -> Option<PathBuf> {
    if compressed.len() * 10 > original.len() * 9 {
        return None;
    }
    let path = blobs.join(format!("{index}.{suffix}"));
    fs::write(&path, compressed).unwrap();
    Some(path)
}

fn optional_include(path: Option<PathBuf>) -> String {
    match path {
        Some(path) => format!("Some(include_bytes!({:?}))", path.display().to_string()),
        None => "None".into(),
    }
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().fold(String::new(), |mut out, byte| {
        let _ = write!(out, "{byte:02x}");
        out
    })
}
